// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMmHSXPkeHQGnM1-Ixubbm9YjaIeq6KCc',
    appId: '1:850170061240:web:9deff4d20c2f54c88a6f4d',
    messagingSenderId: '850170061240',
    projectId: 'atulya-adivasi',
    authDomain: 'atulya-adivasi.firebaseapp.com',
    storageBucket: 'atulya-adivasi.appspot.com',
    measurementId: 'G-2VNLKDJ8E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPOYjsDz7ComNezH0UoJLm--XQMWSMSp8',
    appId: '1:850170061240:android:3f90d1eae7d704d48a6f4d',
    messagingSenderId: '850170061240',
    projectId: 'atulya-adivasi',
    storageBucket: 'atulya-adivasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwkSOEacydFFnL2ddTiv6-JodE_1sXIyI',
    appId: '1:850170061240:ios:387c46559c9492438a6f4d',
    messagingSenderId: '850170061240',
    projectId: 'atulya-adivasi',
    storageBucket: 'atulya-adivasi.appspot.com',
    androidClientId:
        '850170061240-43hl1fl0ndivoqu6e422s8dsg6nk954j.apps.googleusercontent.com',
    iosClientId:
        '850170061240-c4p33jptvm2h1tbajc7eofrgbsbg36db.apps.googleusercontent.com',
    iosBundleId: 'in.i9studios.adivasi.atulya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwkSOEacydFFnL2ddTiv6-JodE_1sXIyI',
    appId: '1:850170061240:ios:387c46559c9492438a6f4d',
    messagingSenderId: '850170061240',
    projectId: 'atulya-adivasi',
    storageBucket: 'atulya-adivasi.appspot.com',
    androidClientId:
        '850170061240-43hl1fl0ndivoqu6e422s8dsg6nk954j.apps.googleusercontent.com',
    iosClientId:
        '850170061240-c4p33jptvm2h1tbajc7eofrgbsbg36db.apps.googleusercontent.com',
    iosBundleId: 'in.i9studios.adivasi.atulya',
  );
}
