name: form_inputs
description: Dart package which manages the form validation.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  checkdigit: ^0.3.1
  formz: ^0.4.1
